<!DOCTYPE html>
<html class="">
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>API V1</title>
		<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
		<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

		<link rel="stylesheet" href="../../../public/css/bulma.min.css">
		<link rel="stylesheet" href="../../../public/css/styles.css">

	</head>

	<body>
		<section class="hero is-fullheight">
			<!-- Hero head: will stick at the top -->
			<div class="hero-head">
				<header class="navbar is-fixed-top">
					<div class="container">
						<div class="navbar-brand">
							<a href="https://www.testarudocreativo.com.mx" class="navbar-item">
								<img src="https://testarudocreativo.com.mx/img/testarudo-brand2.jpg" alt="Logo">
							</a>
							<span class="navbar-burger burger" data-target="navbarMenuHeroA">
								<span></span>
								<span></span>
								<span></span>
          		</span>
						</div>
						<div id="navbarMenuHeroA" class="navbar-menu dis	">
							<div class="navbar-end">
								<a href="https://www.testarudocreativo.com.mx/nosotros.html" class="navbar-item">
									Nosotros
								</a>
								<a href="https://www.testarudocreativo.com.mx/contacto.html" class="navbar-item">
									Contaco
								</a>
								<span class="navbar-item"></span>
							</div>
						</div>
					</div>
				</header>
			</div>

			<!-- Hero content: will be in the middle -->
			<div class="hero-body">
				<div class="container">

					<div class="columns level ">
						<div class="column level-left h">
							<div class="columns">
								<div class="column is-hidden-touch"><img src="https://testarudocreativo.com.mx/img/logo-white.jpg" alt=""></div>

								<div class="column">
									<p class="title">¿Tienes algo que decirnos?</p>
									<p>Envíanos un mensaje y haznos saber lo que piensas; de tus proyectos, de tus gustos, tus ideas, el cosmos y todo lo que se te ocurra.</p>
									<p>&nbsp;</p>
									<p>
										<span class="icon has-text-black is-left">
											<i class="fas fa-envelope"></i>
										</span>
										<a href="mailto:contacto@testarudocreativo.com.mx">contacto@testarudocreativo.com.mx</a>
									</p>
									<p>&nbsp;</p>
									<div class="columns has-text-centered">
										<div class="column">
											<a href="http://twitter.com/testarudoC" target="_blank">
												<span class="icon has-text-black is-left">
													<i class="fab fa-twitter"></i>
												</span>
												@testarudoC
											</a>
										</div>
										<div class="column">
											<a href="http://facebook.com/testarudocreativo" target="_blank">
												<span class="icon has-text-black is-left">
													<i class="fab fa-facebook"></i>
												</span>
												/TestarudoCreativo
											</a>
										</div>
										<div class="column">
											<a href="http://instagram.com/testarudocreativo" target="_blank">
												<span class="icon has-text-black is-left">
													<i class="fab fa-instagram"></i>
												</span>
												/TestarudoCreativo
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="column box level-right ">
							<div class="field">
								<label class="label">Tu Nombre</label>
								<div class="control has-icons-left has-icons-right">
									<input class="input" type="text" placeholder="Nombre" value="">
									<span class="icon is-small is-left">
								<i class="fas fa-user"></i>

								</div>
							</div>

							<div class="field">
								<label class="label">Tu correo</label>
								<div class="control has-icons-left has-icons-right">
									<input class="input" type="email" placeholder="Correo" value="">
									<span class="icon is-small is-left">
								<i class="fas fa-envelope"></i>

								</div>
							</div>

							<div class="field">
								<label class="label">Asunto</label>
								<div class="control">
									<input class="input" type="text" name="" placeholder="Asunto" id="">
								</div>
							</div>

							<div class="field">
								<label class="label">Mensaje</label>
								<div class="control">
									<textarea class="textarea" placeholder="Escríbenos tu mensaje"></textarea>
								</div>
							</div>

							<div class="field">
								<div class="control">
									<label class="checkbox">
										<input type="checkbox">
										Estoy de acuerdo con lost <a href="#">Términos y Condiciones</a>
									</label>
								</div>
							</div>

							<div class="field is-grouped">
								<div class="control">
									<button class="button is-black">Enviar comentario</button>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Hero footer: will stick at the bottom -->
			<div class="hero-foot has-text-centered" style="padding: 10px; box-shadow: 0 -2px 3px rgba(100,100,100,.3); font-size: 0.8em">
				<p class="" style="">
					Todos los derechos reservados
				</p>
				<p>Copyrigth © 2018 <a href="">Testarudo Estudio Creativo</a></p>
			</div>
		</section>

		<script src="../../../public/js/api.js"></script>
	</body>
</html>
